- name: Install native build tools
  yum: state=present name={{ item }}
  with_items:
    - gcc
    - gcc-c++
    - make

- name: Install gcc-c++ make
  yum: name={{item}} state=present
  with_items:
     - gcc-c++
     - make

- name: Add nodejs repository
  shell: curl -sL https://rpm.nodesource.com/setup_8.x | sudo -E bash -

- name: Install nodejs
  yum: name=nodejs-8.12.0 state=present

- name: install i18n
  command: /bin/bash -l -c 'gem install i18n -v 0.7.0'

- name: install compass
  command: /bin/bash -l -c 'gem install compass'

- name: Install npm
  npm: name=npm@latest global=yes state=present

- name: Install cordova
  npm: name=cordova@6.4.0 global=yes state=present

- name: make sure bower is installed
  npm: name=bower@latest global=yes state=present

- name: make sure bower is installed
  npm: name=yarn global=yes state=present

- name: make sure grunt-cli is installed
  npm: name=grunt-cli global=yes state=present

- name: Install ant-apache-regexp
  yum: name=ant-apache-regexp state=present

- name: Install ant-junit
  yum: name=ant-junit state=present

- name: Install ant-trax
  yum: name=ant-trax state=present

- name: Install createrepo
  yum: name=createrepo state=present

- name: Install pip
  yum: name=python-pip state=present

- name: Install aws-cli
  pip: name=awscli state=present

- name: Install libpng-devel
  yum: name=libpng-devel state=present

- name: Install expect
  yum: name=expect state=present

- name: Remove require tty
  lineinfile: regexp="^Defaults\s+requiretty" dest=/etc/sudoers state=absent

- name: Add user go to sudoers group
  lineinfile: dest=/etc/sudoers state=present regexp='^go ALL\=' line='go ALL=(ALL) NOPASSWD:ALL' validate='visudo -cf %s'

- name: Add npm-login-expect shell script
  template:
    src=npm-login-expect.sh.j2
    dest=/etc/npm-login-expect.sh
